name: update schedule

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: install yarn
        run: npm install yarn -g

      - name: Replace and Remove Content in README
        run: |
          sed -i 's|GitHub: \[HerbertHe/iptv-sources\](https://github.com/HerbertHe/iptv-sources)|GitHub: [iptv-sources](https://github.com/ccc-ju/iptv-sources)|g' README.md

          sed -i '/Join discord: \[!\[Discord\](https:\/\/discord\.badge\.ibert\.me\/api\/server\/betxHcsTqa)\](https:\/\/discord\.gg\/betxHcsTqa)/d' README.md

          sed -i '/## Matrix/,/m3u.ibert.me/d' README.md

          sed -i 's|See <https://m3u.ibert.me> to get more.|See <https://m3u.cjuju.us.kg/> to get more.|g' README.md

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Auto-update README: replaced links and removed sections"
          git push origin HEAD:gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - run: yarn install
      - run: yarn build
      - run: yarn m3u

      - name: "Jekyll theme"
        run: mv ./_config.temp.yml ./m3u/_config.yml

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./m3u
          enable_jekyll: true
          cname: m3u.cjuju.us.kg
