name: Update README

on:
  workflow_dispatch:  # 支持手动触发
  schedule:
    # 每5分钟运行一次（可根据需要调整）
    - cron: '*/5 * * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Replace README Content
      run: |
        # 使用 sed 命令替换 README 中的内容
        sed -i 's|GitHub: \[HerbertHe/iptv-sources\](https://github.com/HerbertHe/iptv-sources)|GitHub: [iptv-sources](https://github.com/ccc-ju/iptv-sources)|g' README.md
        
        # 删除 "Join discord" 相关内容
        sed -i '/Join discord: \[!\[Discord\](https:\/\/discord\.badge\.ibert\.me\/api\/server\/betxHcsTqa)\](https:\/\/discord\.gg\/betxHcsTqa)/d' README.md

        # 删除 "Matrix" 部分
        sed -i '/## Matrix/,/m3u.ibert.me/d' README.md

        # 替换链接内容
        sed -i 's|See <https://m3u.ibert.me> to get more.|See <https://m3u.cjuju.us.kg/> to get more.|g' README.md

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add README.md
        git commit -m "Auto-update README"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
